HikingTrails/Trails/urls.py
from django.urls import path

from HikingTrails.Trails.views import TrailsListView, TrailsDetailView, TrailsCreateView, TrailDeleteView, \
    CommentCreateView, TrailEditView, delete_photo

urlpatterns = [

    path('', TrailsListView.as_view(), name='trail_list'),

    path('<int:pk>/', TrailsDetailView.as_view(), name='trail_details'),

    path('photo/delete/<int:photo_id>/', delete_photo, name='delete_photo'),

    path('create/', TrailsCreateView.as_view(), name='trail_create'),

    path('<int:pk>/delete/', TrailDeleteView.as_view(), name='trail_delete'),

    # path('<int:pk>/trails_confirm_delete/', TrailEditView.as_view(), name='trails_confirm_delete'),

    path('<int:pk>/edit/', TrailEditView.as_view(), name='trail_edit'),

    path('<int:pk>/comment/', CommentCreateView.as_view(), name='comment_trail'),

]

HikingTrails/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from HikingTrails.Trails.views import custom_permission_denied_view

handler403 = custom_permission_denied_view
urlpatterns = [
    # path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),

    # path('set_language/', set_language, name='set_language'),
    path('', include('HikingTrails.Hikers.urls')),
    path('trails/', include('HikingTrails.Trails.urls')),
    path('recommendations/', include('HikingTrails.RecommendationsBook.urls')),

    path('academy/', include('HikingTrails.Academy.urls')),

]
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('set_language/', include('django.conf.urls.i18n')),
)

HikingTrails/Trails/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models

from HikingTrails.Hikers.models import Hiker
from HikingTrails.Trails.validators import validate_image


class Trails(models.Model):
    class Difficulty(models.TextChoices):
        EASY = 'Easy', 'Easy'
        INTERMEDIATE = 'Intermediate', 'Intermediate'
        UPHILL = 'Uphill', 'Uphill'

    name = models.CharField(max_length=100)
    length = models.FloatField(null=True, blank=True)
    image = models.ImageField(upload_to='media', null=True, blank=True, validators=[validate_image])
    difficulty = models.TextField(
        choices=Difficulty.choices,
        default=Difficulty.EASY,
    )
    description = models.TextField(help_text='Enter a description of the trail')
    elevation_gain = models.FloatField(null=True, blank=True)
    hiker = models.ForeignKey(Hiker, on_delete=models.CASCADE, related_name='trails')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TrailPhotos(models.Model):
    trail = models.ForeignKey(Trails, on_delete=models.CASCADE, related_name='photos')
    image = models.ImageField(upload_to='trail_images/')
    description = models.CharField(max_length=255, blank=True)


class Comment(models.Model):
    trail = models.ForeignKey(to=Trails, on_delete=models.CASCADE, related_name='comments')
    # user = models.ForeignKey(Hiker, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # hiker_id = models.ForeignKey(to=Hiker, on_delete=CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.user} on {self.trail}'

HikingTrails/Trails/forms.py
# forms.py
from django import forms

from .models import Comment, TrailPhotos, Trails


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class TrailPhotosForm(forms.ModelForm):
    class Meta:
        model = TrailPhotos
        fields = ['image', 'description']


class TrailForm(forms.ModelForm):
    class Meta:
        model = Trails
        exclude = ['hiker']

HikingTrails/Trails/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from .forms import CommentForm, TrailPhotosForm, TrailForm
from .models import Comment, TrailPhotos
from .models import Trails
from ..Hikers.models import Hiker


class TrailsCreateView(CreateView):
    model = Trails
    template_name = 'trails/trail_create.html'
    fields = ['name', 'length', 'image', 'difficulty', 'description', 'elevation_gain']
    success_url = reverse_lazy('trail_list')

    def form_valid(self, form):
        form.instance.hiker = self.request.user
        return super().form_valid(form)


class TrailsListView(ListView):
    model = Trails
    template_name = 'trails/trail_list.html'
    context_object_name = 'trails'


class TrailsDetailView(DetailView):
    model = Trails
    template_name = 'trails/trail_details.html'
    context_object_name = 'trail'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comments = Comment.objects.filter(trail=self.object)
        paginator = Paginator(comments, 5)  # Show 5 comments per page
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj
        context['form'] = CommentForm()
        context['photo_form'] = TrailPhotosForm()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'comment' in request.POST:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.trail = self.object
                comment.user = request.user
                comment.save()
        elif 'photo' in request.POST:
            photo_form = TrailPhotosForm(request.POST, request.FILES)
            if photo_form.is_valid():
                photo = photo_form.save(commit=False)
                photo.trail = self.object
                photo.save()
        return redirect('trail_details', pk=self.object.pk)


class TrailDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Trails
    template_name = 'trails/trail_confirm_delete.html'
    success_url = reverse_lazy('trail_list')  # Replace with your trail list view name

    def test_func(self):
        trail = self.get_object()
        return self.request.user == trail.hiker and self.request.user.is_approved


class TrailEditView(UpdateView):
    model = Trails
    form_class = TrailForm
    template_name = 'trails/trail_edit.html'

    def form_valid(self, form):
        form.instance.hiker = self.request.user
        trail = form.save(commit=False)
        trail.save()
        return redirect('trail_details', pk=trail.pk)


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'trails/comment_trail.html'
    fields = ['text']
    success_url = reverse_lazy('trail_list')

    def form_valid(self, form):
        user = self.request.user
        if not Hiker.objects.filter(id=user.id).exists():
            return HttpResponseForbidden("User does not exist.")
        form.instance.user = user
        form.instance.trail_id = self.kwargs['pk']
        if user.is_authenticated:
            return super().form_valid(form)
        else:
            return self.handle_no_permission()


def custom_permission_denied_view(request, exception):
    return render(request, '403.html', status=403)


@login_required
def delete_photo(request, photo_id):
    photo = get_object_or_404(TrailPhotos, id=photo_id)
    if photo.trail.hiker == request.user:
        photo.delete()
    return redirect(reverse('trail_details', args=[photo.trail.id]))

templates/trails/comment_trail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>Add Comment</h1>
    {% if user.is_authenticated %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p>Comment from {{ user }}</p>
            {#        <button type="submit">Save</button>#}
            <button type="submit" class="center-button">
                <img src="{% static 'images/save_icon.png' %}" alt="Save" style="width: 30px; height: 30px;">
                Submit
            </button>
        </form>
    {% else %}
        <p>You must be logged in to comment!</p>
    {% endif %}
{% endblock %}

templates/trails/trail_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Confirm Delete</h1>
    <p>Are you sure you want to delete the trail "{{ object.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm</button>
    </form>
    <a href="{% url 'trail_list' %}">Cancel</a>
{% endblock %}

templates/trails/trail_create.html
<!-- trails_form.html -->
{% extends 'base.html' %}
{% block content %}
    <h1>Create Trail</h1>
    {% if user.is_authenticated %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="center-button">Save</button>
        </form>
    {% else %}
        <p>You must be logged in to create a trail!</p>
    {% endif %}
{% endblock %}

templates/trails/trail_details.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ trail.name }}, by {{ trail.hiker }}</h1>
    <p>Location: {{ trail.location }}</p>
    <p>Difficulty: {{ trail.get_difficulty_display }}</p>
    <p>Description: {{ trail.description }}</p>
    <p>Length: {{ trail.length }} m</p>
    <p>Elevation Gain: {{ trail.elevation_gain }} m</p>
    {% if trail.image %}
        <img src="{{ trail.image.url }}" alt="{{ trail.name }}" style="width: 300px; height: auto;">
    {% else %}
        <p>No image available for this trail.</p>
    {% endif %}
    <a href="{% url 'trail_list' %}" class="button btn-lg btn-primary">Back to trails list</a>
    {% if user.is_authenticated %}
        <a href="{% url 'trail_edit' trail.pk %}" class="button btn-lg btn-primary">Edit trail</a>
        <a href="{% url 'comment_trail' trail.pk %}" class="button btn-lg btn-primary">Comment trail</a>
        <a href="{% url 'trail_delete' trail.pk %}" class="button btn-lg btn-primary">Delete</a>

    {% else %}
        <p>You must be logged!</p>
    {% endif %}
    <h2>Comments</h2>
    <div class="comment-section">
        {% for comment in page_obj %}
            <div class="fa-comments-o">
                <p><strong>{{ comment.user.username }}</strong> said:</p>
                <p>{{ comment.text }}</p>
                <p><em>Posted on {{ comment.created_at }}</em></p>
            </div>
        {% empty %}
            <p>No comments yet.</p>
        {% endfor %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>

    <h2>Photos</h2>
    <div style="background-color: #f9f9f9; padding: 20px; border-radius: 5px;">
        {% for photo in trail.photos.all %}
            <div class="photo" style="margin-bottom: 15px; padding: 10px; border: 1px solid #ddd; border-radius: 5px;">
                <img src="{{ photo.image.url }}" alt="{{ photo.description }}" style="width: 300px; height: auto;">
                <p>{{ photo.description }}</p>
                {% if user.is_authenticated and trail.hiker == user %}
                    <form method="post" action="{% url 'delete_photo' photo.id %}" style="display:inline;"
                          onsubmit="return confirm('Are you sure you want to delete this photo?');">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                {% endif %}
            </div>
        {% empty %}
            <p>No photos yet.</p>
        {% endfor %}
    </div>

    <h2>Upload Photo</h2>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ photo_form.as_p }}
                    <button type="submit" name="photo" class="btn btn-primary center-button">Upload</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/trails/trail_edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit Trail</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {% if user.is_authenticated %}
            <button type="submit" class="btn btn-primary center-button">Save changes</button>
        {% else %}
            <p>You must be logged in to edit a trail!</p>
        {% endif %}
    </form>
{% endblock %}

templates/trails/trail_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5 grp-transparent">
        <h1 class="mb-4">Trails List</h1>
        <ul class="list-group">
            {% for trail in trails %}
                <li class="list-group-item">
                    <a href="{% url 'trail_details' trail.pk %}" class="text-decoration-none">{{ trail.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/trails/trails_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Confirm Delete</h1>
    <p>Are you sure you want to delete the trail "{{ object.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm</button>
    </form>
    <a href="{% url 'trail_list' %}">Cancel</a>
{% endblock %}

templates/trails/trails_create.html
<!-- trails_form.html -->
{% extends 'base.html' %}
{% block content %}
    <h1>Create Trail</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}